apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: 479547938987.dkr.ecr.us-east-2.amazonaws.com/aws-springapp:latest
          ports:
            - containerPort: 8080
